spring:
  application:
    name: users
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    jpa:
      database-platform:
        org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
h2-server:
  port: 8082

server:
  port: 8081
  servlet:
    context-path: /

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    ac.ou.tm470.user: DEBUG